title: Lorena Corona. Publicista de carrera y marketiniana de profesión.
email: lorenacorona95@gmail.com
description: Estrategia y creatividad digital. Especialista en llevar la publicidad a un nuevo escenario digitalizado para conectar mejor a las marcas con las personas.
baseurl: ""
url: "https://lorenacorona.com"
twitter_username: jekyllrb
github_username:  jekyll

sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
