title: Alberto Gallego
email: albertogc2793@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      Hi! I am software developer and I like building products
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://albertogallego.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
paginate: 3
paginate_path: "/blog/page:num/"

sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
